import { Metadata } from 'next';
import React from 'react';
import { Roboto } from 'next/font/google';
import SideNav from './ui/sidenav';
import 'leaflet/dist/leaflet.css';
import './globals.css';

const roboto = Roboto({
  weight: ['500'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Spaces',
  description: 'Generated by Khadar',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
     
      <body className={`${roboto.className} antialiased`}>
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
          <div className="w-full flex-none md:w-64">
            <SideNav />
          </div>
          <div className="flex-grow p-6 md:overflow-y-auto md:p-12">{children}</div>
        </div>
      </body>
    </html>
  );
}